- hosts: "{{ server | default('hdoop_client') }}"
  roles:
    - common
    - openjdk
    - maven
    - alluxio_yarn

- hosts: "{{ server | default('hadoop_slave') }}"
  roles:
    - common
    - alluxio_conf
